version: '3.0'

services:
  watch:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/model/CrakTextSummarizer
    env_file:
      - .env
    command: "bash -c 'conda env update --prefix ./env --file text_summarizer.yml --prune; activate text_summarizer; python -m nltk.downloader punkt; nodemon src/main.py'"

  shell:
    build: .
    entrypoint: [ "/bin/bash" ]
    stdin_open: true
    tty: true
    volumes:
      - .:/model/CrakTextSummarizer
    env_file:
      - .env
